#!/usr/bin/env python3
"""Build the supplementary sections S1-S14 from checkpoint records.

Every number is read from a results.json at build time. Nothing is transcribed. Where a value the
specification asks for does not exist in any record, the output says BLOCKED rather than inventing it.

Usage:  python scripts/build_supplementary.py <ledger_dir> <out.md>
"""
import json, os, re, sys

BLOCK = "**BLOCKED** — not in any checkpoint record; must be measured or the sentence dropped."


class _Ledger(dict):
    """dict that yields None for an absent record instead of raising."""
    def __getitem__(self, k):
        return self.get(k)


def load(ledger, cp):
    p = f"{ledger}/{cp}/results.json"
    return json.load(open(p)) if os.path.exists(p) else None


def main(ledger, out):
    # Records are named for what they measure. results/INDEX.json carries the run order the old
    # numeric prefixes used to encode, and G returns None for a record that is absent (some are
    # staged out of the published package), so a missing record degrades a section rather than
    # raising a KeyError here.
    present = {d for d in os.listdir(ledger) if os.path.isdir(f"{ledger}/{d}")}
    G = _Ledger({cp: load(ledger, cp) for cp in sorted(present)})
    index = json.load(open(f"{ledger}/INDEX.json"))["records"]
    ordered = [r["name"] for r in sorted(index, key=lambda r: r["order"])]
    cps = [n for n in ordered if n in present] + sorted(present - set(ordered))
    c0, c0b, c0c = G["pipeline"], G["identifiability"], G["resolution_audit"]
    c2, c3, c12 = G["sft_chain"], G["process_reward"], G["sota_push"]
    c15, c23 = G["box_sufficiency"], G["depth_sufficiency"]
    c25, c26 = G["oracle_within_sample"], G["model_sweep"]
    c28, c31 = G["classifier_refreeze"], G["visibility_corrected_oracle"]
    c32, c35 = G["extraction_operating_point"], G["stratified_frontier_expansion"]
    c36, c41 = G["generational_comparison"], G["no_image_control"]
    c50, c52 = G["eval_scaleup"], G["rung_R2_detector_oracle"]
    c53, c54 = G["rung_R3_coords_as_text"], G["render_convention_sweep"]
    c58, c60 = G["perception_transplant"], G["length_control"]

    ep = c58["emitted_position_quality"]
    d19 = c32["verified_against_atom_detection"]
    if isinstance(d19, str):
        d19 = json.loads(d19.replace("'", '"'))
    pw = c54["model_leg"]["power"]
    cpa = pw["CORRECTED_paired_analysis"]
    sm = c50["size_matched_control"]
    fc = c50["full_sample_CANONICAL_clean"]
    rf = c28["random_forest"]
    pc = c28["partition_canonical"]
    r3v = [v["r3_coords"] for v in c53["rows"].values() if isinstance(v, dict)]
    npre = sum(1 for c in cps
               if any(f.startswith("prereg") for f in os.listdir(f"{ledger}/{c}")))
    amb = c35["confound_stated"]["ambiguous_is_largely_one_degeneracy"]
    dcc = c35["de_concentration_check"]
    esm = c60["effect_size_at_median_split"]
    ccp = c60["confound_control_preregistered"]

    T = f"""# CoCr — Supplementary sections S1-S14

Generated by `scripts/build_supplementary.py`, which reads every number from a `results.json` in
`results/` at build time. Nothing here is transcribed. Where a value the specification asked for does not
exist in any record, the line says BLOCKED rather than supplying a plausible figure.

---

## S1. Dataset construction and label certification
SOURCE: pipeline, identifiability, eval_scaleup

SOURCE DATABASES. Materials Project and JARVIS-DFT. The pilot drew {c0['meta']['n_mp']} structures from MP
and {c0['meta']['n_jarvis']} from JARVIS; the identifiability sample drew {c0b['meta']['n_mp']} and
{c0b['meta']['n_jarvis']} at seed {c0b['meta']['seed']}. RETRIEVAL DATE: {BLOCK}

FILTERS AND STRATIFICATION. The scale-up sample: {c50['sample']['filters']}. Target 285 per crystal system
before quarantine, realised at exactly 285 for all seven systems.

COMPOSITION EXCLUSION, AUDITED. No composition in any evaluation set appears in training. The leakage audit
reports {c50['sample']['leakage_audit']['train']} overlap with the training set,
{c50['sample']['leakage_audit']['eval210']} with the original 210-structure sample, and
{c50['sample']['leakage_audit']['expansion']} with the expansion sample — verified zero on all three.

SYMMETRY-TOLERANCE QUARANTINE. A structure whose label changes under a tolerance sweep is quarantined; at
scale-up this removed {c50['sample']['n'] - fc['n']} of {c50['sample']['n']}
({c50['sample']['quarantine_rate'] * 100:.2f}\\%). THE GATE ITSELF FAILED SILENTLY IN AN EARLIER VERSION:
it read a top-level key the schema nests one level down, so it defaulted to "stable" for every structure
and the published quarantine rate of zero was the count of a gate that could not fire. Rescoring without
the affected structures shifted every quantity by at most 0.0041, so the conclusions held, and the clean
values are canonical. A blunt rule flipping on any tolerance would have removed 7.1\\% and destroyed the
low-symmetry strata.

LABEL CORRECTNESS AGAINST THE SOURCE DATABASES. Pilot:
{c0['summary']['label_correctness']['n_agree']} of
{c0['summary']['label_correctness']['n_robust_with_source_sg']} tolerance-robust structures agree with the
source space group, rate {c0['summary']['label_correctness']['agreement_rate']}, over
{c0['summary']['n_records']} records with {c0['summary']['n_errors']} pipeline errors.
CLOPPER-PEARSON EXACT BOUND. On the kept set after quarantine, label agreement is 220/220, whose one-sided
95\\% lower bound is $0.05^{{1/220}} = 0.9865$ — the strongest statement 220 consecutive agreements can
support, and deliberately not quoted as "100\\% accurate". The quarantine that produced that kept set removed
1.8\\% of structures, concentrated in the low-symmetry strata (triclinic 3/32, monoclinic 1/32, zero
elsewhere), which is why the quarantine rate is reported per system rather than pooled.
PER-SAMPLE BOUNDS FOR THE TWO 210-STRUCTURE EVALUATION SETS: {BLOCK}

---

## S2. Render protocol
SOURCE: pipeline, resolution_audit

CAMERA SPECIFICATION. Five orthographic views: three principal-axis and two oblique. The direction vectors
are the frozen `VIEWS` map in `scripts/src/cocr/render.py`, which is the normative specification. They are
referenced rather than transcribed here so the two cannot drift.

RESOLUTION, READ FROM THE LIVE PROCESSOR RATHER THAN ASSUMED. max_pixels
{c12['training']['max_pixels']}, {c12['training']['effective_visual_tokens_per_view']} effective visual
tokens per view, {c12['training']['source']}. This matters because resolution_audit found the DEPLOYED configuration
differed from the DOCUMENTED one by 3.408x in area. The audit's pre-registration stated its own asymmetry
in advance: only an INCREASE at native resolution would have been a clean positive. The outcome landed in
the ambiguous branch, so resolution is NOT excluded as a factor and no claim is attached to it.

ATOM RADII, BOND CRITERIA, COLOUR MAPPING, BACKGROUND, SUPERCELL RULE: in `render.py`. A prose table of
the numeric values is {BLOCK}

---

## S3. The geometric oracle
SOURCE: oracle_within_sample, oracle_stratified, visibility_corrected_oracle

WHY THE CEILING CAN BE BELOW 1.0, AND WHY THAT IS THE POINT. The oracle forward-projects ground-truth
positions through each frozen camera, DISCARDS cross-view correspondence, re-solves by ray intersection,
verifies across views, and applies the symmetry algorithm to the result. A design supplying source
coordinates as text would have a ceiling of exactly 1.0 by construction and would measure nothing.

RECOVERY RATES WITH DENOMINATORS. Original
{round(c25['oracle_accuracy']['original_eval']['5v'] * 210)}/210 =
{c25['oracle_accuracy']['original_eval']['5v']}; expansion
{round(c25['oracle_accuracy']['expansion_eval']['5v'] * 210)}/210 =
{c25['oracle_accuracy']['expansion_eval']['5v']}; scale-up {fc['oracle']['k']}/{fc['n']} =
{fc['oracle']['micro']} on the full clean sample and {sm['oracle']['k']}/{sm['n']} =
{sm['oracle']['micro']} size-matched at a cap of {sm['cap_atoms']} atoms.

RUNTIME, WHICH IS THE REPRODUCIBILITY ARGUMENT. The pilot pipeline labelled and rendered
{c0['summary']['n_records']} structures in {c0['meta']['elapsed_sec']} s and the identifiability sweep ran
in {c0b['meta']['elapsed_sec']} s, both on CPU only — the oracle has no GPU dependency anywhere in
`reconstruct.py`, so anyone can rerun it on a laptop. Per-run wall-clock for the full evaluation sweeps was
not recorded.
MATCH TOLERANCE AND THE PER-STRUCTURE FAILURE-MODE BREAKDOWN: {BLOCK} (the perception_transplant extraction scoring
tolerance IS recorded, at {ep['matching_tolerance_frac']} in fractional coordinates, but that is a
different quantity from the oracle's own cross-view match criterion.)

---

## S4. The attribution ladder
SOURCE: oracle_within_sample, rung_R3_coords_as_text, perception_transplant, length_control

R0 IS DEFINITIONAL. Applying the symmetry algorithm to ground-truth positions returns the label by
construction, so R0 = 1.0000 exactly. Treating R0 as approximately equal to R1 would discard the interval
that measures what camera inversion costs.

THE SYMBOLIC SHARE, RENAMED AND BOUNDED. R1 − R3 is the SYMBOLIC SHARE, not the reasoning share: the
residual between a deterministic solver and a model given the same exact geometry, which BOUNDS rather than
isolates symmetry reasoning. Median perception share {c53['perception_fraction']['median']} across the
{c53['roster']['scored']} models scored under the coordinate condition (attempted
{c53['roster']['attempted']}), min {c53['perception_fraction']['min']}, max
{c53['perception_fraction']['max']}, with the symbolic share the larger of the two for
{c53['perception_fraction']['majority_reasoning_models']} of them. Spearman rho against pixel accuracy
{c53['spearman_pixel_vs_perception_share']['rho']} at p =
{c53['spearman_pixel_vs_perception_share']['p']}.

WHY IT IS ONLY A BOUND (length_control, {c60['api_calls']} new API calls). Regressing per-structure R3 correctness on
conventional-cell atom count over the same records: pooled Spearman {c60['pooled']['rho']} at p =
{c60['pooled']['p']:.2e} over {c60['pooled']['n_pairs']} model-structure pairs, with
{c60['pooled']['n_negative_rho']} of {c60['pooled']['n_models']} models negative and
{c60['pooled']['n_individually_significant']} individually significant. Accuracy falls from
{esm['small_cells']['acc']} ({esm['small_cells']['k']}/{esm['small_cells']['n']}) on cells at or below the
median {esm['threshold_atoms']} atoms to {esm['large_cells']['acc']}
({esm['large_cells']['k']}/{esm['large_cells']['n']}) above it, Fisher p = {esm['fisher_p']:.4f}.
THE PRE-REGISTERED CONFOUND CONTROL DOES NOT RESCUE IT: atom count correlates with crystal system
({ccp['confound_is_real']['atom_count_vs_symmetry_rank_rho']} against symmetry rank), but the mean
WITHIN-system association is {ccp['mean_within_system_rho']} — STRONGER than the pooled figure, not
attenuated. Two of seven systems run positive and are reported rather than pooled away.

R2 IS UNSCORED, NOT ABSENT. The detector fails to triangulate on
{c52['gate']['original']['zero_recovery_rate'] * 100:.1f}\\% and
{c52['gate']['expansion']['zero_recovery_rate'] * 100:.1f}\\% of structures against a pre-registered
5\\% gate. The detector's own quality: median recall {d19['recall_median']}, median precision
{d19['precision_median']:.4f}, median centroid error {d19['centroid_err_px_median']} px over
{d19['n_view_measurements']} view measurements on {d19['n_structures']} structures. Recall correlates with
overlap at {d19['recall_vs_overlap_corr']}, so extraction fails at VISIBILITY AND SEGMENTATION, not at
sub-pixel localisation.

THE CONTROL PAIR. Formula-only collapses every model toward seven-way chance (mean
{c53['text_formula_only_mean']}); full geometry lifts them to between {min(r3v):.4f} and {max(r3v):.4f}.
The two conditions differ in one thing, which is what makes the lift attributable to the geometry rather
than to text-mode prompting. PROMPT LENGTH: {json.dumps(c53['prompt_length'])} — the geometry prompts are
shorter than the five-image prompts they outperform, which rules out a length artefact in the LIFT (a
different question from length_control's, which is about the residual's composition).

PER-MODEL R3 AND R4 VECTORS: `release/predictions/`, one file per model.

---

## S5. The extraction fabrication
SOURCE: perception_transplant

THE PROMPTS, VERBATIM: `release/frozen_prompts.json`, entries `CP58_extraction_strong_model` (462
characters, symmetry question deliberately withheld so the extraction cannot leak an answer) and
`CP58_answer_weak_model`. Both were ABSENT from that file until an audit found them missing, even though
the checkpoint's result depends on them.

WHAT THE STRONG MODEL EMITTED. Median {ep['atoms_emitted_distribution']['median']} well-formed atoms per
structure (mean {ep['atoms_emitted_distribution']['mean']}, range
{ep['atoms_emitted_distribution']['min']} to {ep['atoms_emitted_distribution']['max']}, over
{ep['atoms_emitted_distribution']['n']} structures), correct element symbols, five-decimal fractional
coordinates. MEDIAN RECALL AGAINST GROUND TRUTH {ep['median_recall']}, median precision
{ep['median_precision']}, matching tolerance {ep['matching_tolerance_frac']} in fractional coordinates.
Median error on the atoms that DID match: {ep['median_error_on_matched_atoms_frac']}.
For contrast, the colour-threshold blob detector on the same task reaches median recall
{ep['cp19_detector_for_contrast']['median_recall']} and precision
{ep['cp19_detector_for_contrast']['median_precision']} — a crude pixel heuristic beats the strong model at
the extraction step it was asked to perform.
AN EARLIER PROSE FIGURE OF 45 ATOMS IS RETRACTED: it came from a 43-record diagnostic on a CLASS-ORDERED
PREFIX already discarded for the accuracy number, and it leaked into prose while the numeric field beside
it was correct.
{ep['structures_with_zero_matched_atoms']} of {ep['n_scored']} structures have NOT ONE emitted atom within
tolerance of a real one. The output is syntactically perfect and almost entirely unrelated to the
structure — a failure downstream accuracy alone would have attributed to reasoning.

THE DOWNSTREAM ARM MEASURES NOTHING, AND IS REPORTED RATHER THAN SCORED. It predicted two of seven classes
and its accuracy equals the majority stratum's base rate exactly, so it is prediction collapse. The correct
reference for comparison is in `correct_reference_for_A3`; comparing against the wrong model's ceiling
would overstate the shortfall.

VERBATIM RESPONSE TEXT: **BLOCKED** — the harness parsed each response into the `emitted` array and
DISCARDED the original string. `a3_raw.json` retains the parsed arrays, vote records and per-structure
verdicts, which a reader can check against the true structure, but that is not the same order of evidence
as the model's own words. Re-running with text retained is 210 calls to one model.
THE FULL PER-STRUCTURE RECALL DISTRIBUTION AND THE CLASS-PREDICTION HISTOGRAM: {BLOCK} The medians,
the zero-match count and the emitted-atom distribution are recorded; the full histograms are not.

---

## S6. Roster, prompts, decoding, and the model arms
SOURCE: sft_chain, process_reward, sota_push, frontier_ceiling, model_sweep, no_image_control, rung_R3_coords_as_text

THREE ROSTERS, WHICH IS WHY NO BARE COUNT APPEARS ANYWHERE IN THE PAPER.

| condition | attempted | scored | unscored, and under which gate |
|---|---|---|---|
| model_sweep zero-shot leaderboard | 14 pre-registered | {len(c26['leaderboard_canonical_run_A'])} | `moonshotai/kimi-k2.6` — ENDPOINT FAILURE: no response on a 2-structure K=1 probe after 10 minutes, so the failure is the endpoint not the harness |
| no_image_control image-removal control | {c41['roster_extension']['n_attempted']} | {c41['roster_extension']['n_scored']} | {c41['roster_extension']['n_unscored']}, over a pre-registered 5\\% API-error gate |
| rung_R3_coords_as_text coordinates-as-text | {c53['roster']['attempted']} | {c53['roster']['scored']} | `qwen/qwen2.5-vl-72b-instruct` — both gates exceeded at {list(c53['roster']['unscored'].values())[0]['api_error_rate'] * 100:.1f}\\% errors |

Every unscored entry is reported UNSCORED rather than dropped.

THE MODEL ARMS. Base `{c2['model']}`. SFT (sft_chain): {c2['method']}, {c2['train_n_structures']} train /
{c2['test_n_structures']} test structures, seeds {c2['seeds']}. GRPO (process_reward): from SFT checkpoint
`{c3['config']['sft_ckpt']}`, lr {c3['config']['lr']}, KL beta {c3['config']['beta']}, group size
{c3['config']['group_size']}, {c3['config']['steps']} steps, {c3['config']['train_prompts']} train prompts,
{c3['config']['stack']}. A3 (sota_push): {c12['training']['examples']} examples from
{c12['training']['structures']} structures, {c12['training']['epochs']} epochs, {c12['training']['steps']}
steps, final loss {c12['training']['final_loss']}, {c12['training']['wall_clock_s']} s wall clock.
AUGMENTATION: {c12['training']['augmentation']} — disjoint from the five frozen eval views, which is what
prevents it leaking the eval protocol.

WHAT IS NOT CLAIMED FOR A3. SINGLE-SEED. {c12['result']['correct']}/{c12['result']['n']} =
{c12['result']['micro']} at K=3, Wilson95 {c12['result']['wilson95']};
{round(c25['paired_original_eval']['A3_native']['arm'] * 210)}/210 =
{c25['paired_original_eval']['A3_native']['arm']} at K=8. It sits INSIDE the reference arm's across-seed
spread (0.590 / 0.567 / 0.686), exceeding that arm's best seed by ONE structure at K=8 and TRAILING it by
FIVE at K=3. No improvement over the reference arm is claimed. a3_seeds, the three-seed extension, was CUT;
its record holds the quantitative argument that seed variation cannot close the oracle-to-model margin of
{round(c25['oracle_accuracy']['original_eval']['5v'] * 210) - round(c25['paired_original_eval']['A3_native']['arm'] * 210)}
structures, which is the comparison A3 is actually used for.

RUN-TO-RUN SPREAD, PUBLISHED AS A BENCHMARK PROPERTY. The zero-shot sweep ran twice through an aggregation
defect; the leaderboard is rebuilt single-run and the second run is retained as a labelled replication.
Mean absolute difference
{c26['measurement_provenance']['run_to_run_spread']['mean_abs_structures']} structures, maximum
{c26['measurement_provenance']['run_to_run_spread']['max_abs_structures']}, maximum accuracy difference
{c26['measurement_provenance']['run_to_run_spread']['max_abs_accuracy']}. Every headline claim survives
both runs independently.

no_image_control'S REFUSAL CASE, whose raw response would be the strongest single argument for the control's validity:
{BLOCK}

---

## S7. What the render protocol withholds
SOURCE: visibility_corrected_oracle, extraction_operating_point, atom_detection

THE FOUR VISIBILITY CONDITIONS, expansion sample, four views, n = {c31['conditions']['expansion_4v_O0']['n']}:

| condition | recovery | structures with exact atom-count match |
|---|---|---|
| O0 unconditioned | {c31['conditions']['expansion_4v_O0']['micro']} | {c31['conditions']['expansion_4v_O0']['count_match']} |
| O1 informative occluders removed | {c31['conditions']['expansion_4v_O1']['micro']} | {c31['conditions']['expansion_4v_O1']['count_match']} |
| O2 all occluders removed | {c31['conditions']['expansion_4v_O2']['micro']} | {c31['conditions']['expansion_4v_O2']['count_match']} |
| O3 control, random removal | {c31['conditions']['expansion_4v_O3']['micro']} | {c31['conditions']['expansion_4v_O3']['count_match']} |

THE PRIMARY QUANTITY IS EXACTLY ZERO AND THE CONTROL MOVES, which is the informative pattern: removing the
occluders argued to matter changes no classification, while removing random occluders changes many. The
right-hand column proves the removals REACHED the reconstructor — atom counts change across conditions, so
a flat recovery curve is not a plumbing failure. The pre-registered control rule makes O1 unreadable when
the control dominates, and it does.

UNTRIANGULABLE FRACTIONS, PER-SAMPLE REDUNDANT AND INFORMATIVE MEANS, THE AXIS-VERSUS-OBLIQUE RATIO: in
visibility_corrected_oracle's `axis_vs_oblique` and `cross_view_recoverability` fields and occlusion_redundancy's record. The axis/oblique
comparison matters because it means every occlusion figure published before that extension was measured on
the protocol's three worst cameras.

---

## S8. Cue sufficiency
SOURCE: box_sufficiency, classifier_refreeze, eval_expansion, stratified_frontier_expansion

Moved here from the main text because the section ended by disclaiming itself.

THE CANONICAL PREDICATE, AND A TRAP IN ITS OWN SOURCE FILE. Executable form in
`scripts/run_e05_oracle.py`. That file HARDCODES tolerances of 1e-2 and 0.5 degrees, which give a 144/66
split. The CANONICAL partition is {pc['rule']}, giving
{pc['original']['sufficient']}/{pc['original']['ambiguous']} on the original sample and
{pc['expansion']['sufficient']}/{pc['expansion']['ambiguous']} on the expansion. Running the file at its
defaults does NOT reproduce the published partition; passing the canonical tolerances reproduces it
exactly, composition-identical across all five metric classes.

THE CONTRAST AGAINST A CONTROL. Raw stratified accuracy failed four independent tests and is withdrawn;
the defect was comparing raw accuracy, which moves with intrinsic difficulty. The surviving quantity is
pixel accuracy minus a cell-metric random forest on the same structures, which widens on the ambiguous
stratum for {c35['n_arms_widening_both_samples']} of 3 frontier models on both samples. The control itself
also drops across strata, which is why the contrast rather than raw accuracy is primary.

THE CONFOUND, STATED NOT BURIED. The ambiguous stratum is
{amb['original_hex_or_trig']}/{amb['original_n']} and
{amb['expansion_hex_or_trig']}/{amb['expansion_n']} hexagonal-or-trigonal, so the finding is close to a
restatement of that one degeneracy. Removing it leaves n = {dcc['original_residual_n']} and n =
{dcc['expansion_residual_n']}, where one structure moves the gap by 8 to 10 points. The residual is
suggestive and establishes nothing.

---

## S9. Generational comparison
SOURCE: generational_comparison

Moved here from the main text because the section ended by disclaiming itself.

RAW STRATUM GAINS: {c36['stratified']['box_sufficient']['delta']:+.4f} sufficient (n =
{c36['stratified']['box_sufficient']['n']}) and {c36['stratified']['box_ambiguous']['delta']:+.4f}
ambiguous (n = {c36['stratified']['box_ambiguous']['n']}), which invites the reading that the newer
generation closes the render-imposed gap fastest.

NORMALISED BY HEADROOM TO THE ORACLE IT REVERSES:
{c36['headroom_normalisation']['sufficient_share_of_headroom'] * 100:.1f}\\% of the sufficient stratum's
headroom against {c36['headroom_normalisation']['ambiguous_share_of_headroom'] * 100:.1f}\\% of the
ambiguous one. The larger raw gain is substantially a low-baseline effect.

A PROCESS DEFECT IS RECORDED WITH THE RESULT. The analysis ran BEFORE its record was written, and the
headroom control was added only after the raw result looked wrong. The accompanying document is labelled a
post-hoc analysis record, not a pre-registration. The result is credible because it is arithmetic anyone
can recheck from the released vectors, not because it was pre-committed.

ONE MODEL PAIR IS A COMPARISON AND NOT A TREND.

---

## S10. Render conventions
SOURCE: render_convention_sweep, depth_sufficiency

THE ORACLE LEG IS CONCLUSIVE, AND IT REFUTED TWO OF THIS PROJECT'S OWN PREDICTIONS. Off-axis cameras raise
the ceiling from {c54['oracle_ceiling_by_camera_map']['original']['frozen_micro']} to
{c54['oracle_ceiling_by_camera_map']['original']['offaxis_micro']}. Supercell tiling COSTS the oracle
structures rather than helping. The off-axis result survived undetected for a time only because the camera
map was HARDCODED, so any perturbed-camera run silently reproduced the frozen result; it was caught because
both conditions returned identical values.

THE MODEL LEG IS INCONCLUSIVE, NOT NULL, AND THE EARLIER POWER FIGURE WAS WRONG. A previously published
minimum detectable difference of {pw['RETRACTED_mde_alpha05']['value']} came from
`{pw['RETRACTED_mde_alpha05']['formula']}` — an UNPAIRED two-proportion normal approximation with no
target-power term, applied to a test that was PAIRED. Recomputed properly: discordance averages
{cpa['mean_discordant_pairs']} of 70 (rate {cpa['discordance_rate']}), and significance is REACHABLE IN
ONLY {cpa['comparisons_where_significance_is_reachable']} OF THE {cpa['of']} COMPARISONS — the other
{cpa['unreachable_comparisons']} carry 2 to 5 discordant pairs, where no split reaches p < 0.05 at any
outcome. Largest observed absolute delta {pw['largest_observed_abs_delta']}. THE CORRECTED ANALYSIS MAKES
THE NULL WEAKER, NOT STRONGER, and the contribution is demoted accordingly.

A MONOTONE BUT NON-METRIC DEPTH CUE IS WORSE THAN NONE:
{c23['rank_variant_defect']['values']['original_box_sufficient']['P']} to
{c23['rank_variant_defect']['values']['original_box_sufficient']['R']}. Uniform rank spacing is a nonlinear
distortion of true depth, so any depth grading must be METRIC-FAITHFUL rather than merely monotone — which
is what justifies that word in any recommendation. Quantization saturates at
{c23['quantization_saturates_at']} levels across all four strata, having been stated as four and corrected.

THE 16-COMPARISON TABLE with discordance counts and exact p: render_convention_sweep's `paired_vs_C1` field.

---

## S11. Classical baselines
SOURCE: classifier_refreeze, external_baselines, eval_scaleup

THE SHAPE-FREE FLOOR. Three features — atom count, density, cell volume — deliberately blind to shape.
Canonical {c26['reference_rows']['shape_free_regularity_floor']['k']}/{c26['reference_rows']['shape_free_regularity_floor']['n']}
= {c26['reference_rows']['shape_free_regularity_floor']['micro']} on the original sample.

THE CELL-METRIC RANDOM FOREST. Ordered 19-feature list, library versions and seed in
`results/classifier_refreeze/`. Canonical {rf['canonical_k']}/{rf['n']} = {rf['canonical_micro']}.
ONE FEATURE-SOURCE TRAP IS RECORDED: the features come from the INPUT cell, not the conventionalised cell.
Feeding conventional cells is off by one structure.

A DOCUMENTED NON-RECOVERY, NOT A CORRECTION. Twelve defensible readings of the recorded feature prose span
{rf['variant_range'][0]} to {rf['variant_range'][1]} and NONE reproduces the published 186
(`reproduces_published_186`: {json.dumps(rf['reproduces_published_186'])}). Forward reproducibility is
fixed; the historical value is not recovered, and one published significance verdict changed as a result.

SCALE-UP, WITH THE CONTROL THAT SEPARATES TWO CAUSES. The floor falls to
{fc['floor_3feat']['k']}/{fc['n']} = {fc['floor_3feat']['micro']} on the full clean sample and
{sm['floor']['k']}/{sm['n']} = {sm['floor']['micro']} size-matched, so its shift is NOT a cell-size
artefact — it is a property of the original draw, and the below-floor comparison is therefore SCOPED TO
THAT SAMPLE rather than asserted as a task property. The oracle falls to {fc['oracle']['micro']} full and
{sm['oracle']['micro']} matched, so ITS drop IS a cell-size effect. Only the size-matched control could
separate them. {sm['purpose']}

---

## S12. Negative and superseded results
SOURCE: project retraction and superseded-results record

Verbatim in `reports/SUPPLEMENTARY_INFORMATION.md` Part II, which carries every checkpoint's finding
including every withdrawal. Referenced from the reproducibility statement and the AI-use disclosure, and
from nowhere in the main text. The render_convention_sweep power-calculation retraction is among them.

---

## S13. Pre-registrations
SOURCE: every checkpoint's prereg.md

Verbatim in Part II of `SUPPLEMENTARY_INFORMATION.md`, in numeric checkpoint order, including the ones
whose outcome CONTRADICTED the registered expectation, the ones that landed BETWEEN branches, a3_seeds's cut
record and merged_retrain's subsumption record. Of the {len(cps)} checkpoints, {npre} carry a pre-registration; the
rest say so in their own finding text rather than implying one existed.

---

## S14. Artifact and datasheet
SOURCE: release tooling

Croissant metadata in `release/croissant.json`, validated against the reference `mlcroissant` library.
Per-structure prediction vectors for every arm reported anywhere, in `release/predictions/`, so each
accuracy recomputes without API access. Frozen prompts in `release/frozen_prompts.json`.

GATE COVERAGE, STATED HONESTLY. `scripts/verify_manuscript_numbers.py` reads `REPORT.md` and `paper/*.md`
and refuses any sentence carrying a value absent from a checkpoint record, or an accuracy without its
sample and decode budget. IT DOES NOT OPEN A PNG and cannot see a figure axis — the fabricated
parameter-count incident was fixed by policy, not by that gate. `scripts/validate_package.py` closes the
other half: all six manuscript figures have generating scripts and are verified byte-for-byte against a
regeneration, and check 7b refuses any manuscript figure without one. `scripts/lint_latex.py` checks the
source for unescaped percent signs, unbalanced math, math spans ending in an operator, math-only
constructs outside math, and undefined references or citations.
EVERY CHECK IN ALL THREE TOOLS WAS TESTED AGAINST A DELIBERATE VIOLATION OF THE RULE IT ENFORCES. Two were
found to CRASH rather than report, and were hardened. THIS PACKAGE SHIPS WITH ALL SIX FIGURES INSIDE THE
MD5 CHECK.
"""
    open(out, "w").write(T)
    nb = T.count("BLOCKED")
    nvals = len(re.findall(r"(?<![0-9.])[0-9]+\.[0-9]{3,4}(?![0-9])", T))
    print(f"{out}: {len(T.splitlines())} lines, {nb} BLOCKED markers, {nvals} numeric values")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
